name: testchallange
description: My challange.
publish_to: 'none'  
version: 1.0.2

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  # pay: ^1.1.1
  in_app_purchase: 

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.0 
  firebase_core:

flutter:
  uses-material-design: true
  assets:
    - Icon/